/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */
declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;
  }

  interface HTMLAttributes {}
}


import {
  HibiscusTextComponent as HibiscusText
} from './hibiscus-text/hibiscus-text';

declare global {
  interface HTMLHibiscusTextElement extends HibiscusText, HTMLStencilElement {
  }
  var HTMLHibiscusTextElement: {
    prototype: HTMLHibiscusTextElement;
    new (): HTMLHibiscusTextElement;
  };
  interface HTMLElementTagNameMap {
    "hibiscus-text": HTMLHibiscusTextElement;
  }
  interface ElementTagNameMap {
    "hibiscus-text": HTMLHibiscusTextElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "hibiscus-text": JSXElements.HibiscusTextAttributes;
    }
  }
  namespace JSXElements {
    export interface HibiscusTextAttributes extends HTMLAttributes {
      text?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
